import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

// class
public class Main_9251_LCS_G5 {
	
	static Integer dp[][];
	static String A;
	static String B;
	
	// main
	public static void main(String[] args) throws IOException {
		
		// br
		BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
		
		A = br.readLine();
		B = br.readLine();
		
		dp = new Integer[B.length()][A.length()];
		
		System.out.println(LCS(0, 0));
		
	} // end of main
	
	// LCS
	static int LCS(int idx_B, int idx_A) {
		
		if (idx_B == B.length() || idx_A == A.length()) {
			return 0;
		}
		
		if (dp[idx_B][idx_A] != null) {
			return dp[idx_B][idx_A];
		}
		
		if (B.charAt(idx_B) == A.charAt(idx_A)) {
			return dp[idx_B][idx_A] = Math.max(LCS(idx_B+1, idx_A+1)+1, 1);
		} else {
			return dp[idx_B][idx_A] = Math.max(LCS(idx_B+1, idx_A), LCS(idx_B, idx_A+1));
		}
		
	} // end of LCS
	
} // end of class

/*
ACAYKP
CAPCAK
ACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYKACAYK
CAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCACAPCA
*/
